### ISSUE TITLE
Fix error code: Process finished with exit code -1073740771 (0xC000041D)

### ISSUE THREAD

**Issue by hodTwito** [capi-bgu/capi#11]
Need to figure out where, when and why this code accrue and fix it or catch it so it won't stop the system from running.

**Comment by yuvalkh** [comment]
Where: In CameraCollector waiting loop.
When: when there are many inputs in the collectors so the cpu is working hard.
Why: This error probably occurs because of the busy waiting on the camera that causes the cpu to go crazy.

The fix: removed the busy waiting by removing if timing condition and adding sleep

**Comment by hodTwito** [comment]
After adding processing with threads this error occurs again- when CPU gets to 100% usage.
